"""Models package – exposes all Pydantic models."""

from strava_mcp.models.activity import (
    ActivityType,
    ActivityVisibility,
    ActivityZone,
    Comment,
    CreateActivityRequest,
    DetailedActivity,
    Lap,
    LatLng,
    MetaActivity,
    MetaAthlete,
    PhotosSummary,
    PolylineMap,
    SportType,
    SummaryActivity,
    SummaryGear,
    TimedZoneRange,
    UpdatableActivity,
)
from strava_mcp.models.athlete import (
    DetailedAthlete,
    HeartRateZoneRanges,
    PowerZoneRanges,
    SummaryAthlete,
    SummaryClub,
    ZoneRange,
    ZoneRanges,
    Zones,
)
from strava_mcp.models.segment import (
    DetailedSegment,
    DetailedSegmentEffort,
    ExplorerResponse,
    ExplorerSegment,
    LocalLegend,
    SummarySegment,
    SummarySegmentEffort,
    Xoms,
)
from strava_mcp.models.misc import (
    ActivityFilter,
    ActivityStats,
    ActivityTotal,
    AltitudeStream,
    BaseStream,
    CadenceStream,
    ClubActivity,
    DetailedClub,
    DetailedGear,
    DistanceStream,
    HeartrateStream,
    LatLngStream,
    MapUrls,
    MovingStream,
    PowerStream,
    Route,
    SmoothGradeStream,
    SmoothVelocityStream,
    StreamSet,
    TemperatureStream,
    TimeRangePreset,
    TimeStream,
    Upload,
    Waypoint,
)
from strava_mcp.models.filters import (
    AnalysisFilter,
    ActivityFilter as FilterActivityFilter,
    preset_to_epoch_range,
    human_label,
)
from strava_mcp.models.responses import (
    ActivityDataPoint,
    ActivityInsightResponse,
    AggregatedStatsResponse,
    HRZoneAnalysisResponse,
    HRZoneBucket,
    PeriodComparisonResponse,
    PeriodLabel,
    PeriodMetrics,
    PerformanceTrendResponse,
    PersonalRecord,
    PersonalRecordsResponse,
    PowerAnalysisResponse,
    PowerZoneBucket,
    SegmentComparisonResponse,
    SegmentEffortSummary,
    SportBreakdown,
    WeeklyBreakdownResponse,
    WeekSummary,
)

__all__ = [
    # activity
    "ActivityType", "ActivityVisibility", "ActivityZone", "Comment",
    "CreateActivityRequest", "DetailedActivity", "Lap", "LatLng",
    "MetaActivity", "MetaAthlete", "PhotosSummary", "PolylineMap",
    "SportType", "SummaryActivity", "SummaryGear", "TimedZoneRange",
    "UpdatableActivity",
    # athlete
    "DetailedAthlete", "HeartRateZoneRanges", "PowerZoneRanges",
    "SummaryAthlete", "SummaryClub", "ZoneRange", "ZoneRanges", "Zones",
    # segment
    "DetailedSegment", "DetailedSegmentEffort", "ExplorerResponse",
    "ExplorerSegment", "LocalLegend", "SummarySegment",
    "SummarySegmentEffort", "Xoms",
    # misc
    "ActivityFilter", "ActivityStats", "ActivityTotal", "AltitudeStream",
    "BaseStream", "CadenceStream", "ClubActivity", "DetailedClub",
    "DetailedGear", "DistanceStream", "HeartrateStream", "LatLngStream",
    "MapUrls", "MovingStream", "PowerStream", "Route", "SmoothGradeStream",
    "SmoothVelocityStream", "StreamSet", "TemperatureStream",
    "TimeRangePreset", "TimeStream", "Upload", "Waypoint",
    # filters
    "AnalysisFilter", "FilterActivityFilter", "preset_to_epoch_range",
    "human_label",
    # responses
    "ActivityDataPoint", "ActivityInsightResponse", "AggregatedStatsResponse",
    "HRZoneAnalysisResponse", "HRZoneBucket", "PeriodComparisonResponse",
    "PeriodLabel", "PeriodMetrics", "PerformanceTrendResponse",
    "PersonalRecord", "PersonalRecordsResponse", "PowerAnalysisResponse",
    "PowerZoneBucket", "SegmentComparisonResponse", "SegmentEffortSummary",
    "SportBreakdown", "WeeklyBreakdownResponse", "WeekSummary",
]
